### ISSUE TITLE
ButtonPillar Rotation Behaviour is Unexpected

### ISSUE THREAD

**Issue by wschella** [Kinds-of-Intelligence-CFI/animal-ai-unity#20]
A buttonpillar rotation of 90 gives this result:

![image](https://github.com/Kinds-of-Intelligence-CFI/animal-ai-unity-project/assets/9478856/37d40433-e1ed-4289-8e9b-d52c2455c412)

Funny, and could be useful, but probably not what is intented @kozzy97 @alhasacademy96 ?

**Comment by alhasacademy96** [comment]
Yep, i'm aware of that. Also, you will notice that the **y** **axis is fixed at 0**. This is because the spawner_interactivebutton.cs component is not inheriting from Prefab.cs, which all other reward dispensers are, where most of the dispensing logic/code is residing (including SetRotation and GetPosition. Bare with me whilst I create a new Interface for the Pillar Button component where all the functionality is inherited from Prefab.
